### ISSUE TITLE
Loading XSLT Stylesheets from Classpath

### ISSUE THREAD

**Issue by martinklepsch** [eerohele/sigel#2]
Hello again,

I'm wondering if there's any particular support to compile XSLT stylesheets from the classpath or a raw string?

```clj
(str (xslt/transform (xslt/compile-xslt (.getPath to-html-xslt)) content))
```
This works well when the file is a regular file in the filesystem but fails if the file is within a Jar. 

It seems that it would be possible to turn a resource into an input stream and then into a [`StreamSource`](https://docs.oracle.com/javase/8/docs/api/javax/xml/transform/stream/StreamSource.html). 

Am I missing something or is this just something you didn't yet need? Would be happy to provide a PR.

**Comment by martinklepsch** [comment]
But maybe this is also perfectly acceptable:
```clj
(xslt/transform (xslt/compile-source (StreamSource. (io/input-stream to-html-xslt))) (slurp f))
```

**Comment by eerohele** [comment]
I don't think you're missing anything. Your latter example is probably the most straightforward solution at the moment.

Unfortunately, it seems I've made a poor API choice here: similarly to `compile-edn`, `compile-xslt` should probably be a function that accepts anything that can be turned into a `java.io.InputStream`. As in:

```clojure
(xslt/transform (xslt/compile-xslt (io/file "resources/foo.xsl")))

;; or

(xslt/transform (xslt/compile-xslt (io/resource "foo.xslt")))
```

However, I don't want to break backwards compatibility.

One option would be to modify `compile-xslt` such that it checks whether the input argument is already something that can be turned into an `InputStream`. If yes, simply pass it to `io/input-stream`. Otherwise, assume it is a file path and compile it as before.

Maybe checking whether the input arguments ~satisfies~ is an instance of [`IOFactory`](https://github.com/clojure/clojure/blob/4ef4b1ed7a2e8bb0aaaacfb0942729252c2c3091/src/clj/clojure/java/io.clj#L69) would do the trick? Didn't have the time to investigate more than that yet, though.

PR more than welcome if you're up to it!

**Comment by eerohele** [comment]
Actually, it appears that `io/input-stream` already considers a string argument it can't parse into a URL a file path, so the fix is fortunately quite simple.

Pushed v0.2.2. With it, this should work:

```clojure
(xslt/compile-xslt (io/resource "path/to/classpath/stylesheet.xsl"))
```

**Comment by martinklepsch** [comment]
That's a sweet solution! 👍
